const actionTypes = {
    /// Product List Actions
    PRODUCT_LIST_REQUEST: "PRODUCT_LIST_REQUEST",
    PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
    PRODUCT_LIST_FAILED: "PRODUCT_LIST_FAILED",

    /// Product Details Actions
    PRODUCT_DETAILS_REQUEST: "PRODUCT_DETAILS_REQUEST",
    PRODUCT_DETAILS_SUCCESS: "PRODUCT_DETAILS_SUCCESS",
    PRODUCT_DETAILS_FAILED: "PRODUCT_DETAILS_FAILED",

    /// Cart Actions
    CART_ADD_ITEM: "CART_ADD_ITEM",
    CART_REMOVE_ITEM: "CART_REMOVE_ITEM",
};

export default actionTypes;